# This is a config for E2B sandbox template.
# You can use template ID (x950nusgelxxn16c5xxj) or template name (nexus-fuse-rust) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("nexus-fuse-rust") # Sync sandbox
# sandbox = await AsyncSandbox.create("nexus-fuse-rust") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nexus-fuse-rust')

team_id = "c95e0b17-985d-4f1c-88ef-858e33bf5b8b"
memory_mb = 2_048
cpu_count = 4
dockerfile = "e2b.Dockerfile"
template_name = "nexus-fuse-rust"
template_id = "x950nusgelxxn16c5xxj"
