# This is a config for E2B sandbox template.
# You can use template ID (yf6wfidzfb6i7n7iawob) or template name (nexus-sandbox-latest) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("nexus-sandbox-latest") # Sync sandbox
# sandbox = await AsyncSandbox.create("nexus-sandbox-latest") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nexus-sandbox-latest')

team_id = "2550f86d-a39b-4b9e-b551-14d7933b55bc"
dockerfile = "e2b.Dockerfile"
template_name = "nexus-sandbox-latest"
template_id = "yf6wfidzfb6i7n7iawob"
