# This is a config for E2B sandbox template.
# You can use template ID (ohsk388peukvlesxaw6w) or template name (nexus-fuse) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("nexus-fuse") # Sync sandbox
# sandbox = await AsyncSandbox.create("nexus-fuse") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nexus-fuse')

team_id = "c95e0b17-985d-4f1c-88ef-858e33bf5b8b"
dockerfile = "e2b.Dockerfile"
template_name = "nexus-fuse"
template_id = "ohsk388peukvlesxaw6w"
